# Site
repository: # Git repository where your resume will be hosted

# Personal info
name: Zongxing Xie
title: Ph.D. student in ECE
email: zongxing.xie[AT]stonybrook.edu
phone: (631)590-9318
website: zongxingxie.github.io

# Social links
# twitter_username: jekyllrb
github_username:  zongxingxie
# dribbble_username: jekyll
facebook_username: zongxingxie1229
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: zongxingxie
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: zx_profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Zongxing, a third-year Ph.D student in the Department of Electrical and Computer Engineering, Stony Brook Univerisity. 
  Currently, I am working as a Research Assistant under the supervision of [Prof. Fan Ye](http://www.ece.stonybrook.edu/~fanye/index2.html). My research interests center around <mark>Wireless Sensing</mark>, 
  <mark>Ubiquitous Healthcare</mark>, <mark>Deep Learning</mark>, <mark>Edge Computing</mark> and <mark>Embedded System</mark>. 
  Feel free to contact me if interested.
  
  Contact Address: MOCA Lab, [CEWIT](https://www.cewit.org/) 238, 1500 Stony Brook Road, Stony Brook, NY
#  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.
#  You can even add paragraphs by using empty lines like this and add anything else markdown supports such as
#    - Lists
#    - Tables
#    - Links
#    - Images
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in research area, some of my other interests and hobbies are:
  - hiking
  - watching movies
  - [trying out new recipes](https://www.youtube.com/channel/UCE1iTaz744nGffd_tSCGLWw/featured)
footer_show_references: true


sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
